apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-career-buddy-frontend
  namespace: kf-partition-gray
  labels:
    app: ai-career-buddy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-career-buddy-frontend
  template:
    metadata:
      labels:
        app: ai-career-buddy-frontend
    spec:
      containers:
      - name: frontend
        image: harbor.weizhipin.com/arsenal-ai/ai-career-buddy-frontend:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ai-career-buddy-frontend-service
  namespace: kf-partition-gray
  labels:
    app: ai-career-buddy-frontend
spec:
  selector:
    app: ai-career-buddy-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
