apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-career-buddy-combined
  namespace: kf-partition-gray
  labels:
    app: ai-career-buddy-combined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-career-buddy-combined
  template:
    metadata:
      labels:
        app: ai-career-buddy-combined
    spec:
      containers:
      # 后端容器
      - name: backend
        image: harbor.weizhipin.com/arsenal-ai/ai-career-buddy-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ai_career_buddy"
        - name: DB_USERNAME
          value: "mysql_user"
        - name: MYSQL_DSN
          value: "root:root_password_here@tcp(10.98.1.99:3306)/ai_career_buddy?charset=utf8mb4&parseTime=True&loc=Local"
        - name: DB_PASSWORD
          value: "mysql_password"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FILE
          value: "/app/logs/"
        - name: LOG_DIR
          value: "/app/logs"
        - name: UPLOAD_DIR
          value: "/app/uploads"
        - name: MAX_FILE_SIZE
          value: "10485760"
        - name: AI_API_KEY
          value: ""  # 请填入实际的API密钥
        - name: AI_API_SECRET
          value: ""  # 请填入实际的API密钥
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      
      # 前端容器
      - name: frontend
        image: harbor.weizhipin.com/arsenal-ai/ai-career-buddy-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        # 前端容器不需要运行时环境变量，API地址已在构建时硬编码为 localhost:8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: ai-career-buddy-combined-service
  namespace: kf-partition-gray
  labels:
    app: ai-career-buddy-combined
spec:
  selector:
    app: ai-career-buddy-combined
  ports:
    - name: frontend
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: backend
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
